get_vowels("animal") # [a, i, a]
get_vowels("animal") # [a, i, a]
get_vowels("animal") # [a, i, a]
get_vowels("animal") # [a, i, a]
 each in String if each in "aeiou"]
get_vowels("animal") # [a, i, a] each in String- if each in "aeiou"]
get_vowels("animal") # [a, i, a] each in String if each in "aeiou"]
get_vowels("animal") # [a, i, a] each in String if each in "aeiou"]
get_vowels("animal") # [a, i, a]
